# Modelling Horten Wing Conversions

## Mardanpour 2014 properties

In [1]:
import numpy as np

In [3]:
lb2N = 4.448  # N/in
in2m = 0.0254  # m/in

### Stiffness properties

Mardanpour uses NATASHA which employs Hodges' intrinsic theory:

$\begin{bmatrix} \gamma \\ \kappa \end{bmatrix} = \begin{bmatrix} R & S \\ S^\top & T \end{bmatrix}\begin{bmatrix} F \\ M \end{bmatrix} $

All values are given in per unit span. The units of the matrices are:

* $R \leftarrow N^{-1}$

* $S \leftarrow N^{-1} m^{-1}$

* $T\leftarrow N^{-1} m^{-2}$ 


### Root values

In [205]:
R = np.zeros((3,3))
R[0, 0] = 3.09e-10 / lb2N

In [206]:
S = np.zeros((3, 3))
S[0, :] = np.array([7.54, 18.34, 7.83])
S[-2:, 0] = np.array([18.34, 7.83])
S *= 1e-12 * 0
S *= lb2N**-1 * in2m**-1

In [207]:
T = np.zeros((3, 3))
T[0, :] = np.array([3.63, 0, -0.092])
T[1, :] = np.array([0, 5.7, 0.017])
T[2, :] = np.array([-0.092, 0.017, 0.13])
T *= 1e-11
T *= lb2N**-1 * in2m**-2

A zero in compliance matrices implies rigid couplings, teh equivalent of a very high stiffness. Therefore, I'll add terms such that the determinant is non-zero

In [208]:
R[-2:, -2:] = np.diag([1e-11, 1e-11])
np.linalg.det(R)
np.linalg.inv(R)

array([[1.4394822e+10, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+11, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+11]])

In [209]:
F = np.block([[R, S], [S.T, T]])
np.linalg.det(F)
F-F.T

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [204]:
K = np.linalg.inv(F)
K[:3, :3]
np.diag(K)
K

array([[ 3.23624595e+09,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+11,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+11,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.04987046e+07, -1.69971789e+05,  5.69905411e+07],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.69971789e+05,  5.03651190e+07, -6.70649560e+06],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.69905411e+07, -6.70649560e+06,  2.24864852e+09]])

### Tip Values

In [188]:
R_t = np.zeros((3, 3))
R_t[0, 0] = 7.59e-8 * lb2N**-1

In [189]:
S_t = np.zeros((3, 3))
S_t[0, :] = np.array([2.24, 5.23, 0.03])
S_t[-2:, 0] = np.array([5.23, 0.03])
S_t *= 1e-8 * 0
S_t *= lb2N**-1 * in2m**-1
S_t

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [190]:
T_t = np.zeros((3, 3))
T_t[0, :] = np.array([105.46, 0*56.26, -8.81])
T_t[1, :] = np.array([56.26*0, 20.10, 1.68])
T_t[2, :] = np.array([-8.81, 1.68, 10.36])
T_t *= 1e-9
T_t *= lb2N ** -1 * in2m ** -2
T_t

array([[ 3.67498487e-05,  0.00000000e+00, -3.07003761e-06],
       [ 0.00000000e+00,  7.00428559e-06,  5.85432826e-07],
       [-3.07003761e-06,  5.85432826e-07,  3.61016909e-06]])

In [191]:
R_t[-2:, -2:] = np.diag([1e-15, 1e-15])
np.linalg.inv(R_t)

array([[5.86034256e+07, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+15, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+15]])

In [192]:
F_t = np.block([[R_t, S_t], [S_t.T, T_t]])
F_t - F_t.T

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [193]:
K_t = np.linalg.inv(F_t)

In [194]:
np.diag(K_t)

array([5.86034256e+07, 1.00000000e+15, 1.00000000e+15, 2.93227100e+04,
       1.44883639e+05, 3.02592902e+05])

In [195]:
K_t.dot(F_t)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  1.73472348e-18, -1.88651178e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.41200390e-18,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -6.04158671e-17,  0.00000000e+00,  1.00000000e+00]])

In [196]:
K_t

array([[ 5.86034256e+07,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+15,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+15,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.93227100e+04, -2.11280834e+03,  2.52782426e+04],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.11280834e+03,  1.44883639e+05, -2.52913470e+04],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.52782426e+04, -2.52913470e+04,  3.02592902e+05]])

## Inertia properties

Given in cross sectional inertia per unit span in $lb\,s^2$

### Root

In [199]:
I_root = np.diag([67, 2.7, 66.2])*1e-2*lb2N / 9.81
I_root

array([[0.30378797, 0.        , 0.        ],
       [0.        , 0.0122422 , 0.        ],
       [0.        , 0.        , 0.30016065]])

In [200]:
I_tip = np.diag([0.2, 0.014, 0.18]) * 1e-2 * lb2N / 9.81

In [201]:
I_tip

array([[9.06829766e-04, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 6.34780836e-05, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 8.16146789e-04]])

## Lumped Masses


Pilot

In [210]:
mu_pilot= 0.9
mu_pilot *= lb2N /in2m / 9.81

In [211]:
mu_pilot

16.065881673047752

In [212]:
position = np.array([0, -10, -10]) * in2m

In [213]:
position

array([ 0.   , -0.254, -0.254])

Engines

In [214]:
mu_engine = 0.03
mu_engine *= lb2N /in2m / 9.81
mu_engine

0.5355293891015918

In [221]:
j_engine = np.diag(3*[2.6]) * lb2N * in2m / 9.81

In [222]:
j_engine

array([[0.02994352, 0.        , 0.        ],
       [0.        , 0.02994352, 0.        ],
       [0.        , 0.        , 0.02994352]])